# Deploy www-redirects on cloud.gov
---
name: deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-development:
    if: github.ref == 'refs/heads/develop'
    name: deploy (development)
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push www-redirects --vars-file vars.development.yml --strategy rolling
          org: gsa-datagov
          space: development
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 10
          timestamp=$(date +%s)
          host=www-redirects-dev-datagov.app.cloud.gov
          [ "301 https://www.data.gov/test?${timestamp}" = "$(curl --output /dev/null --write-out '%{http_code} %{redirect_url}' --fail --silent https://${host}/test?${timestamp})" ]

  deploy-staging:
    if: github.ref == 'refs/heads/main'
    name: deploy (staging)
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push www-redirects --vars-file vars.staging.yml --strategy rolling
          org: gsa-datagov
          space: staging
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 10
          timestamp=$(date +%s)
          host=www-redirects-stage-datagov.app.cloud.gov
          [ "301 https://www.data.gov/test?${timestamp}" = "$(curl --output /dev/null --write-out '%{http_code} %{redirect_url}' --fail --silent https://${host}/test?${timestamp})" ]

  deploy-production:
    if: github.ref == 'refs/heads/main'
    name: deploy (production)
    needs:
      - deploy-staging
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push www-redirects --vars-file vars.production.yml --strategy rolling
          org: gsa-datagov
          space: prod
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 10
          timestamp=$(date +%s)
          host=www-redirects-prod-datagov.app.cloud.gov
          [ "301 https://www.data.gov/test?${timestamp}" = "$(curl --output /dev/null --write-out '%{http_code} %{redirect_url}' --fail --silent https://${host}/test?${timestamp})" ]
